name: Host Angular app in GitHub
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building and Deploying...
      uses: JamesIves/github-pages-deploy-action
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /angular-gh-action/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/angular-gh-action
