name: Host Angular app in GitHub
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building and Deploying...
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /angular-gh-action/
        deploy_branch: gh-pages
